// Apaga las luces (Lights Out) — pure state machine. Pressing a cell toggles it
// and its orthogonal neighbors; clear the board (all off) to win. Puzzles are
// generated by scrambling from all-off, so they are always solvable.

export const SIZE = 5;

// Difficulty: more scramble presses at higher levels (a puzzle scrambled with
// K presses is solvable in ≤ K presses).
export function scrambleCount(level) {
  return Math.min(SIZE * SIZE - 1, 3 + level);
}

function emptyGrid(size) {
  return new Array(size * size).fill(false);
}

export function applyToggle(grid, idx, size) {
  const r = Math.floor(idx / size);
  const c = idx % size;
  const g = grid.slice();
  const flip = (rr, cc) => {
    if (rr >= 0 && rr < size && cc >= 0 && cc < size) {
      g[rr * size + cc] = !g[rr * size + cc];
    }
  };
  flip(r, c);
  flip(r - 1, c);
  flip(r + 1, c);
  flip(r, c - 1);
  flip(r, c + 1);
  return g;
}

export function isAllOff(grid) {
  return grid.every((v) => !v);
}

export function scramble(size, count, rng = Math.random) {
  let g = emptyGrid(size);
  for (let i = 0; i < count; i++) {
    g = applyToggle(g, Math.floor(rng() * size * size), size);
  }
  // Never hand the player an already-solved board.
  if (isAllOff(g)) g = applyToggle(g, Math.floor(rng() * size * size), size);
  return g;
}

export function createInitialState(overrides = {}) {
  const size = overrides.size ?? SIZE;
  const level = overrides.level ?? 1;
  const grid = overrides.grid ?? scramble(size, scrambleCount(level));
  return {
    size,
    level,
    grid,
    moves: 0,
    phase: 'playing', // 'playing' | 'won'
    stats: { maxLevel: 1, solved: 0 },
    ...overrides,
  };
}

export const initialState = createInitialState();

export const actions = {
  toggle: (idx) => ({ type: 'TOGGLE', idx }),
  nextLevel: () => ({ type: 'NEXT_LEVEL' }),
  restart: () => ({ type: 'RESTART' }),
  resetStats: () => ({ type: 'RESET_STATS' }),
  hydrate: (persisted) => ({ type: 'HYDRATE', persisted }),
};

export function lucesReducer(state, action) {
  switch (action.type) {
    case 'HYDRATE': {
      const p = action.persisted || {};
      const level = typeof p.level === 'number' ? p.level : state.level;
      return {
        ...state,
        level,
        stats: p.stats ? { ...state.stats, ...p.stats } : state.stats,
        grid: scramble(state.size, scrambleCount(level)),
        moves: 0,
        phase: 'playing',
      };
    }

    case 'TOGGLE': {
      if (state.phase !== 'playing') return state;
      const grid = applyToggle(state.grid, action.idx, state.size);
      const moves = state.moves + 1;
      if (isAllOff(grid)) {
        return {
          ...state,
          grid,
          moves,
          phase: 'won',
          stats: {
            solved: state.stats.solved + 1,
            maxLevel: Math.max(state.stats.maxLevel, state.level),
          },
        };
      }
      return { ...state, grid, moves };
    }

    case 'NEXT_LEVEL': {
      const level = state.level + 1;
      return {
        ...state,
        level,
        grid: scramble(state.size, scrambleCount(level)),
        moves: 0,
        phase: 'playing',
      };
    }

    case 'RESTART':
      return {
        ...state,
        grid: scramble(state.size, scrambleCount(state.level)),
        moves: 0,
        phase: 'playing',
      };

    case 'RESET_STATS':
      return { ...state, stats: { maxLevel: 1, solved: 0 } };

    default:
      return state;
  }
}
